"""
MAIN.PY

The driver code for the app
Developer: Joshua Bode
COMP16321 Coursework 2


Free sprite sheet sourced from here: https://ninjikin.itch.io/fruit?download
Bomb sprite created by Joshua Bode
Boss key image data generated by ChatGPT
Font from: https://www.dafont.com/arcade-classic-2.font
Background from: https://limezu.itch.io/kitchen

"""

from app import App

App()
